<?php

return [
    [
        'title'      => 'DEV-ME',
        'icon'       => 'fas fa-users-cog',
        'icon_color' => 'icc-28',
        'sl'         => 1000,
        'children' => [
            [
                'title'      => 'Dashboard',
                'icon'       => 'fas fa-tachometer-alt',
                'route'      => 'me.dashboard',
                'for_active' => 'me.dashboard',
                'icon_color' => 'text-encodex-secondary',
                'permit'     => 'me.dashboard',
                'meta'       => 'Encodex Estiaque Ahmed Khan',
            ],
            [
                'icon'       => 'fas fa-users',
                'title'      => 'Users',
                'route'      => 'me.users.index',
                'for_active' => 'me.users',
                'permit'     => 'me_user.view',
                'icon_color' => 'icc-81',
            ],
            [
                'icon'   => 'fas fa-user-shield',
                'title'  => 'Roles',
                'route'  => 'me.roles.index',
                'for_active' => 'me.roles',
                'permit' => 'me_role.view',
                'icon_color' => 'icc-38',
            ],
            [
                'icon'   => 'fas fa-history',
                'title'  => 'Activity Log',
                'route'  => 'me.activity.index',
                'for_active' => 'me.activity',
                'permit' => 'me_activity.view',
                'icon_color' => 'icc-40',
            ],
            [
                'permit' => 'me_setting.configurations',
                'title'  => 'Configurations',
                'icon'   => 'fas fa-wrench',
                'route'  => 'me.configurations.edit',
                'for_active' => 'me.configurations.edit',
                'icon_color' => 'icc-67',
            ],
            [
                'permit' => 'me_setting.mail',
                'title'  => 'Mail Configuration',
                'icon'   => 'fas fa-at',
                'route'  => 'me.mail-config.edit',
                'for_active' => 'me.mail-config',
                'icon_color' => 'icc-38',
            ],
            [
                'permit' => 'me_setting.sms',
                'title'  => 'SMS Configuration',
                'icon'   => 'fas fa-sms',
                'route'  => 'me.sms-config.edit',
                'for_active' => 'me.sms-config',
                'icon_color' => 'icc-81',
            ],
            [
                'permit' => 'me_sms.view',
                'title'  => 'SMS Log & Balance',
                'icon'   => 'fas fa-comment-dollar',
                'route'  => 'me.sms-log.index',
                'for_active' => 'me.sms-log',
                'icon_color' => 'icc-40',
            ],
            [
                'permit' => 'me_mail.view',
                'title'  => 'Mail Log',
                'icon'   => 'fas fa-envelope-open-text',
                'route'  => 'me.mail-log.index',
                'for_active' => 'me.mail-log',
                'icon_color' => 'icc-55',
            ],
            [
                'icon'   => 'fas fa-trash-alt',
                'title'  => 'Clear Data',
                'route'  => 'me.data.clear.form',
                'for_active'  => 'me.data.clear.form',
                'permit' => 'me.clearData',
                'icon_color' => 'text-danger',
            ],
            [
                'icon'   => 'fas fa-paint-brush',
                'title'  => 'Theme Info',
                'route'  => 'me.theme',
                'for_active'  => 'me.theme',
                'permit' => 'me.theme',
                'icon_color' => 'icc-55',
            ],
                        [
                'icon'   => 'fas fa-envelope',
                'title'  => 'Email Templates',
                'route'  => 'me.mail-layout-preview',
                'for_active'  => 'me.mail-layout-preview',
                'permit' => 'me.mailLayoutPreview',
                'icon_color' => 'text-secondary',
            ],
            [
                'icon'   => 'fas fa-bars',
                'title'  => 'Menus',
                'route'  => 'me.menus.index',
                'for_active'  => 'me.menus',
                'permit' => 'me_menus.view',
                'icon_color' => 'text-primary',
            ],
        ]
    ],
    // [
    //     'title'      => 'Roles',
    //     'icon'       => 'fas fa-book',
    //     'icon_color' => 'text-secondary',
    //     'route'      => 'admin.roles.index',
    //     'for_active' => 'admin.roles',
    //     'permit'     => 'me.dashboard',
    // ],
    // [
    //     'title'      => 'Users',
    //     'icon'       => 'fas fa-book',
    //     'icon_color' => 'text-secondary',
    //     'route'      => 'admin.users.index',
    //     'for_active' => 'admin.users',
    //     'permit'     => 'me.dashboard',
    // ],

];



